planning_task:
  description: >
    Take the user's input `{goal}` and produce:
      - An array `agents` of agent names & roles
      - An array `tasks` mapping each agent to their responsibilities
  expected_output: >
    A YAML object with top-level keys `agents`, `tasks`, and `structure`, for example:
    agents:
      - name: planner
        role: Goal Planner Agent
      - name: writer
        role: File Writer Agent
      - name: packager
        role: Packager Agent

    tasks:
      - agent: planner
        task: planning_task
      - agent: writer
        task: writing_task
      - agent: packager
        task: packaging_task
  agent: planner